### PR TITLE
Comprehensive user behavior testing

### PR DESCRIPTION
**Pull request by zsajjad**
In order to make our demo app close to real life applications, I have added 2 screens to application.

## PR Details

- feat: add TS support
- refactor: moved to React Native Testing Library from Enzyme
- feat: add React Navigation to make our demo app closer to real life applications
- feat:  search & save country feature to demonstrate differences between unit, integration and e2e testing.
- feat: components required to implement this feature are also part of our app now.

## User Story

App starts from same react native's default screen with small additions of toggle button and a button to navigate to search screen. On search screen there is an autocomplete to search from list of countries. User can select a country and that will be stored in local storage. On next app launch this screen will display the selected country. Selected country can be removed by pressing the on item.

## Notes
I have retained all the current tests, just refactored them to RNTL.

### CODE REVIEW

**Comment by markoa** [comment]
@zsajjad Thanks for this. Do you have any thoughts on why the build on Semaphore is failing? We can't merge anything if the build is red.

**Comment by zsajjad** [comment]
@markoa its passing all checks now.

**Comment by AleksandarCole** [comment]
Hi @zsajjad, great news on the first pipeline. Unfortunately, it seems like the iOS build block is failing on the second pipeline after the promotion:
https://semaphore-demos.semaphoreci.com/workflows/e13466c2-a7ae-44c7-b3fe-b692166e3231?pipeline_id=d20aded9-bc57-4abb-b5e2-c26e5f387969

**Comment by zsajjad** [comment]
@AleksandarCole can you please trigger build again.

**Comment by markoa** [comment]
@zsajjad We've given you access to the repo on GitHub and organization on Semaphore so that you can trigger the promotion yourself.

**Comment by zsajjad** [comment]
Thanks @markoa 
IMHO node v14 should be available on VM by default. For now I have added installation to build scripts but that's not an ideal solution.

**Comment by zsajjad** [comment]
It passed! 🥳 🎊

**Pull request merged**
